tier: 1
checkpoints: [
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_1.pt', # Google Colab
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_2.pt', # Google Colab
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_3.pt', # Google Colab
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_4.pt', # Google Colab
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_5.pt', # Google Colab
  '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_6.pt' # Google Colab
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_1.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_2.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_3.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_4.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_5.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_6.pt' # Local machine
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_1.pt', # Kaggle
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_2.pt', # Kaggle
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_3.pt', # Kaggle
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_4.pt', # Kaggle
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_5.pt', # Kaggle
  # '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier_6.pt' # Kaggle
]
conditional: True
