tier: 6
checkpoints: [
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier1_step28928_loss-1_2691.pt', # Google Colab
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier2_step34016_loss-1_1956.pt', # Google Colab
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier3_step34848_loss-1_1984.pt', # Google Colab
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier4_step10912_loss-1_3524.pt', # Google Colab
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier5_step4352_loss-1_3193.pt', # Google Colab
  # '/content/drive/My Drive/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier6_step8192_loss-1_6498.pt' # Google Colab
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_1.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_2.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_3.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_4.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_5.pt', # Local machine
  # '~/Repositories/Tremendous Storytime/MelNet/chkpt/tremendous_storytime_checkpoint_tier_6.pt' # Local machine
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier1_step28928_loss-1_2691.pt', # Kaggle
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier2_step34016_loss-1_1956.pt', # Kaggle
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier3_step34848_loss-1_1984.pt', # Kaggle
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier4_step10912_loss-1_3524.pt', # Kaggle
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier5_step4352_loss-1_3193.pt', # Kaggle
  '../input/tremendous-storytime-checkpoint-1/tremendous_storytime_checkpoint_tier6_step8192_loss-1_6498.pt' # Kaggle
]
conditional: True
